const langs = {
    locale: 'vi-VN',
    messages: {
        'vi-VN': {
            common: {
                currency: 'Đ',
                title: "KVAY",
                descript: "KVay- Vay Online Mọi Lúc Mọi Nơi",
                currentVer: 'Phiên bản hiện tại',
                loading: 'Đang tải...',
                success: "Thành công",
                fail: "Thất bại",
                error: "Xảy ra lỗi",
                tip: "Nhắc nhở",
                tip2:'Nhắc nhở',
                confirm: "Xác nhận",
                cancel: "Hủy",
                message: "Tin tức",
                network: 'Mạng',
                request: 'Call',
                loginfail: 'Đăng nhập thất bại',
                sheZhi: 'Cài đặt',
                submit: "Gửi",
                apply: "Xin vay",
                apply2: "Xin vay ngay",
                next: "Bước tiếp theo",
                feedback: "Ý kiến phản hồi",
                helper: "Trung tâm trợ giúp",
                nonotice: 'Không có thông báo',
                second: 'giây',
                certi: 'Xác thực',
                certino: 'Chưa xác thực',
                certiyes: 'Đã xác thực',
                certiing: 'Đang xác thực',
                certiapply: 'Gửi xác thực',
                certiret: 'Xác thực lại',
                certitrue: 'Xác thực thông qua',
                certibefore: 'Vui lòng đi xác thực trước',
                verfiyCode: 'MÃ OTP',
                copy: 'Sao chép',
                clickCopy: 'Ấn vào để sao chép',
                detail: 'Kiểm tra chi tiết',
                year: 'Năm',
                perfect: 'Hoàn thiện dữ liệu',
                sex1: "Nam",
                sex2: "Nữ",
                front: "Mặt trước",
                reverse: 'Mặt sau',
                hasSelect: 'Tải lên thành công',
                noMsg: '暂无内容',
            },
            tip: {
                qingShuRu: 'Vui lòng điền ',
                qingShuRuYouXiaoDe: 'Vui lòng điền ',
                qingXuanZe: 'Vui lòng chọn ',
                qingXuanZeYouXiaoDe: 'Vui lòng chọn ',
                qingShuRuNeiRong: 'Vui lòng điền nội dung',
                qingShuRuMingCheng: 'Vui lòng điền nội dung',
                qingShuRuYouXiaoDeMingCheng: 'Vui lòng điền nội dung',
                qingShuRuZhuCeDengLuShouJiHao: "Vui lòng điền SDT đăng ký/đăng nhập",
                qingShuRuShouJiHao: "Vui lòng điền SDT",
                qingShuRuZhengQueDeShouJiHao: "Vui lòng điền đúng SDT",
                qingShuRuMiMa: "Vui lòng điền mật khẩu",
                qingShuRuZhengQueDeMiMa: "Vui lòng điền đúng mật khẩu",
                qingShuRuYuanMiMa: "Vui lòng điền mật khẩu cũ",
                qingShuRuZhengQueDeYuanMiMa: "Vui lòng điền đúng mật khẩu cũ",
                qingShuRuXinMiMa: "Vui lòng điền mật khẩu mới",
                qingShuRuZhengQueDeXinMiMa: "Vui lòng điền đúng mật khẩu mới",
                qingShuRuQueRenMiMa: "Vui lòng điền lại mật khẩu mới",
                qingShuRuZhengQueDeQueRenMiMa: "Vui lòng điền đúng mật khẩu mới",
                qingShuRuDuanXinYanZhengMa: "Vui lòng điền mã OTP",
                qingShuRuZhengQueDeDuanXinYanZhengMa: "Vui lòng điền đúng mã OTP",
                qingShuRuZhengShiXingMing: 'Vui lòng điền họ tên của bạn',
                qingShuRuYouXiaoDeZhengShiXingMing: 'Vui lòng điến đúng họ tên của bạn',
                qingShuRuShenFenZhengHao: 'Vui lòng điền số CMT',
                qingShuRuYouXiaoDeShenFenZhengHao: 'Vui lòng điền đúng số CMT',
                qingShuRuYingHangKaHao: 'Vui lòng điền số thẻ',
                qingShuRuYouXiaoDeYingHangKaHao: 'Vui lòng điền đúng số thẻ',
                qingXuanZeYingHang: 'Vui lòng chọn ngân hàng',
                qingXuanZeYouXiaoDeYingHang: 'Vui lòng chọn đúng ngân hàng',
                qingXuanZeXingBie: 'Vui lòng chọn giới tính',
                qingXuanZeYouXiaoDeXingBie: 'Vui lòng chọn đúng giới tính',
                qingXuanZeChuShengRiQi: 'Vui lòng chọn ngày tháng năm sinh',
                qingXuanZeYouXiaoChuShengRiQi: 'Vui lòng chọn đúng ngày tháng năm sinh',
                qingXuanZeShangChuanLeiXing: 'Vui lòng lựa chọn hình thức đăng ảnh',
                qingXuanZeHuoPaiSheTuPian: 'Vui lòng chọn tải ảnh lên hoặc chụp ảnh',
                qingXianWanShanRenLianHeZhengJianXingXi: 'Vui lòng hoàn thiện xác thực khuôn mặt và thông tin CMT trước',
                qingShangChuanZhengJianZhengMianZhaoPian: 'Vui lòng tải ảnh mặt tước CMT',
                qingShangChuanZhengJianFanMianZhaoPian: 'Vui lòng tải ảnh mặt sau CMT',
                qingShangChuanZiPaiZhaoPian: 'Vui lòng tải ảnh tự chụp',
                queRenMiMaCuoWu: "Mật khẩu sai",
                miMaShuoMing: 'Mật khẩu gồm 6-16 ký tự và chứa các chữ cái và số',
                canShuCuoWu: "Tham số sai",
                caoZuoLeiXingCuoWu: 'Thao tác sai',
                huoQuYanZhengMa: "Nhận mã OTP",
                chongXingHuoQu: 'Nhận lại mã OTP',
                dengLuChengGong: "Đăng nhập thành công",
                biaoMingBeiZhu: 'Ghi chú',
                beiZhuGeShi: 'Định dạng ghi chú',
                yiJianFanKuiMiaoShu: 'Vui lòng nhập ý kiến phản hồi của bạn, chúng tôi sẽ không ngừng nỗ lực cải thiện',
                yiRenZhengShiFouChongXiuRenZheng: 'Đã các thực, cần xác thực lại?',
                yingHangKaYiBangDingShiFouChongXiuRenZheng: 'Đã liên kết tài khoản ngân hàng, cần liên kết lại?',
                zhengZaiShiBie: 'Đang xác thực',
                zhengZaiShangChuan: 'Đang tải lên'
            },
            user: {
                regist: "Tạo tài khoản",
                login: "Đăng nhập",
                logout: "Thoát ra",
                logout2: "Thoát đăng nhập",
                forgetPwd: "Quên mật khẩu?",
                loginPwd: "Mật khẩu đăng nhập",
                tradePwd: "Mật khẩu giao dịch",
                jiZhuShouJiHao: "Ghi nhớ SDT",
                ningWeiDengLu: 'Bạn chưa đăng nhập',
                yuanMiMa: "Mật khẩu cũ",
                xinMiMa: "Mật khẩu mới",
                queRenMiMa: "Xác nhận mật khẩu",
                shiFouTuiChuDengLu: 'Thoát đăng nhập?',
                woDeYaoQingMa: 'Mã mời của tôi',
                wanShanZiLiao: 'Hoàn thiện dữ liệu',
                woYiYueDuBingTongYi: 'Tôi đã đọc và đồng ý',
                zhuCeXieYi: '《Thỏa thuận tạo tài khoản》',
                zhaoHuiMiMa: 'Tìm lại mật khẩu',
                yaoQingHaoYou: 'Mời bạn bè',
                yaoQingJiLu: 'Lịch sử mời',
                woDeJiangJing: 'Phần thưởng của tôi',
                daiFanJiangJin: 'Phần thưởng đợi hoàn',
                shouJiHao: 'SDT',
                xingBie: 'Giới tính',
                xingMing: 'Họ tên',
                dianHua: 'SDT',
                diZhi: 'Địa chỉ',
                guanXi: 'Mối quan hệ',
                geRenZhengJian: 'Ảnh chụp CMT',
                renLianShiBie: 'Nhận dạng khuôn mặt',
                shiMingXingXi: 'Thông tin xác thực',
                geRenXingXi: 'Thông tin cá nhân',
                youXiangDiZhi: 'Mail',
                zuiGaoXueLi: 'Học vấn cao nhất',
                hunYinZhuangTai: 'Tình trạng hôn nhân',
                xianJuDiZhi: 'Địa chỉ nơi ở',
                xiangXiDiZhi: 'Địa chỉ cụ thể',
                zhengShiXingMing: 'Họ và tên',
                shenFenZhengHao: 'Số CMT',
                chuShengRiQi: 'Ngày tháng năm sinh',
                zhiXiQingShu: 'Mối quan hệ thân thích',
                jingJiLianXiRen: 'Người liên hệ khẩn cấp',
                gongZuoXingXi: 'Thông tin công việc',
                gongSiMingCheng: 'Tên công ty',
                gongSiDianHua: 'SDT công ty',
                gongSiDiZhi: 'Địa chỉ công ty',
                gongZuoNianXian: 'Kinh nghiệm làm việc',
                xinZi: 'Mức lương',
                yingHang: 'Ngân hàng',
                zhangHuLeiXing: 'Loại tài khoản',
                yingHangXinXi: 'Thông tin ngân hàng',
                suoShuYinHang: 'Ngân hàng',
                yingHangZhangHao: 'Số tài khoản',
                yingHangKaHao: 'số thẻ',
                zhangHaoKaHao: 'Số tài khoản/Số thẻ',
                shouKuanYingHangKa: 'Thẻ ngân hàng nhận tiền',
                chiKaRen: 'Chủ thẻ',
                yunYingShangXingXi: 'Thông tin nhà mạng',
                fackbookXingXi: 'Thông tin Fackbook',
                shiMingXingXiTiShi1: 'Nhắc nhở: Vui lòng điền đúng họ tên và số CMT của bạn, nếu thông tin của bạn không chính xác thì bạn sẽ không thể vay thành công.',
                yingHangKaTianJiaMiaoShu: 'Điền số thẻ nhận tiền của bạn',
                yingHangKaoBangDingMiaoShu1: '1. Sau khi xin vay thành công, chúng tôi sẽ giải ngân vào thẻ ngân hàng này.',
                yingHangKaoBangDingMiaoShu2: '2. Nếu liên kết lại thẻ, thẻ mới sẽ là thẻ nhận tiền giải ngân.',
                yingHangKaoBangDingMiaoShu3: '3. Trong quá trình xin vay, bạn không thể liên kết lại thẻ.',

            },
            bus: {
                timesu: 'Ngày', //Thời gian vay Đơn vị
                yuan: 'Đ',
                eDu: 'Hạn mức',
                jieKuan: 'Vay tiền',
                huanKuan: 'Trả tiền',
                sheYuKeJie: "Hạn mức có thể vay",
                jieKuanJiLu: 'Lịch sử vay',
                yingHangZhuanZhang: 'Ngân hàng chuyển tiền',
                yingHangZhuanZHngShuoMing1: 'Vui lòng thanh toán vào đúng STK ngân hàng bên dưới',
                yingHangZhuanZHngShuoMing2: 'Họ tên + SDT của bạn',
                ziZhuHuanKuan: 'Thanh toán qua bên thứ 3',
                zaloHuanKuan: 'Thanh toán qua ZALO',
                huanKuanFangShiTiShi: 'Hỗ trợ nhiều kênh thanh toán nhanh chóng',
                meiYouJieKuanJiLuTiShi: 'Bạn chưa có đơn vay~~~',
                meiYouHuanKuanXinXiTiShi: 'Hiện tại bạn chưa có đơn cần thanh toán~',
                shouKuanRen: 'Người nhận tiền',
                shouKuanHang: 'Ngân hàng nhận tiền',
                jieKuanXinXi: 'Thông tin vay',
                jingDuXinXi: 'Tiến độ',
                jingKuanJinge: 'Số tiền vay',
                jieKuanLiXi: 'Lãi suất vay',
                jieKuanXieYi: '《Thỏa thuận vay tiền》',
                fuWuFei: 'Phí dịch vụ',
                huanKuan: 'Thanh toán',
                huanKuanXinXi: 'Thông tin thanh toán',
                huanKuaiChengGong: 'Thanh toán thành công',
                huanKuanShiJian: 'Thời gian thanh toán',
                huanKuanZongE: 'Tổng số tiền cần thanh toán',
                jieKuanShiChang: 'Thời gian vay',
                jieKuanShiJian: 'Ngày vay',
                shiJiDaoZhang: 'Nhận tiền',
                liJiHuanKuan: 'Thanh toán ngay',
                ningBengCiHuanKuanJingEYou: 'Số tiền thanh toán lần này là',
                yingHuanJinge: 'Số tiền cần thanh toán',
                yingHuanShiJian: 'Hạn thanh toán',
                yuQiShiJian: 'Thời gian quá hạn',
                yuQiZhiNaiJing: 'Phí phạt quá hạn',
                huanKuanTiShi1: 'Nhắc nhở: Vui lòng kiểm tra số tiền trong tài khoản đủ thanh toán hay không, số tiền không đủ sẽ dẫn đến thanh toán thất bại.',
                borrowStatus10: 'Đang xét duyệt',
                borrowStatus20: 'Xét duyệt tự động thông qua',
                borrowStatus21: 'Xét duyệt tự động không thông qua',
                borrowStatus22: 'Chuyển sang xét duyệt thủ công',
                borrowStatus26: 'Xét duyệt thủ công thông qua',
                borrowStatus27: 'Xét duyệt thủ công không thông qua',
                borrowStatus30: 'Đợi thanh toán',
                borrowStatus35: 'Gia hạn',
                borrowStatus40: 'Đã thanh toán',
                borrowStatus41: 'Thanh toán xin giảm lãi',
                borrowStatus50: 'Đã quá hạn',
                epayHuanKuan: 'Thanh toán qua Epay',
                shouKuanZhangHao: 'Tài khoản nhận tiền',
                huanKuanTiShi: 'Bạn vui lòng thanh toán trước ngày',
                zhangHaoBuCunZi: 'Tài khoản không tồn tại',
                epayHuanKuanTiShi1: 'Vui lòng xác nhận số dư tài khoản của bạn đủ để thanh toán khoản vay.',
                epayHuanKuanTiShi2: 'Nếu số dư không đủ sẽ dẫn đến việc thanh toán khoản vay thất bại!',
                huanKuanLiuCheng: 'Hướng dẫn thanh toán'
            }
        },
        'zh-CN': {
            common: {
                currency: '￥',
                title: "贝贝花",
                descript: "贝贝花共创美好生活",
                currentVer: '当前版本',
                loading: '正在加载.',
                success: "成功",
                fail: "失败",
                error: "错误",
                tip: "提示",
                tip2: '提醒',
                confirm: "确定",
                cancel: "取消",
                message: "消息",
                network: '网络',
                request: '请求',
                loginfail: '登录失效',
                sheZhi: '设置',
                submit: "提交",
                apply: "申请",
                apply2: "立即申请",
                next: "下一步",
                feedback: "意见反馈",
                helper: "帮助中心",
                nonotice: '暂无公告',
                second: '秒',
                certi: '认证',
                certino: '未认证',
                certiyes: '已认证',
                certiing: '认证中',
                certiapply: '认证申请',
                certiret: '重新认证',
                certitrue: '认证通过',
                certibefore: '请先认证',
                verfiyCode: '验证码',
                copy: '复制',
                clickCopy: '点击复制',
                detail: '查看详细',
                year: '年',
                perfect: '完善资料',
                sex1: "男",
                sex2: "女",
                front: "正面",
                reverse: '反面',
                hasSelect: '已选择',
                noMsg: '暂无内容'
            },
            tip: {
                qingShuRu: '请输入',
                qingShuRuYouXiaoDe: '请输入有效的',
                qingXuanZe: '请选择',
                qingXuanZeYouXiaoDe: '请选择有效的',
                qingShuRuNeiRong: '请输入内容',
                qingShuRuMingCheng: '请输入名称',
                qingShuRuYouXiaoDeMingCheng: '请输入有效的名称',
                qingShuRuZhuCeDengLuShouJiHao: "请输入注册/登录手机号",
                qingShuRuShouJiHao: "请输入手机号",
                qingShuRuZhengQueDeShouJiHao: "请输入正确的手机号",
                qingShuRuMiMa: "请输入密码",
                qingShuRuZhengQueDeMiMa: "请输入正确的密码",
                qingShuRuYuanMiMa: "请输入原密码",
                qingShuRuZhengQueDeYuanMiMa: "请输入正确的原密码",
                qingShuRuXinMiMa: "请输入新密码",
                qingShuRuZhengQueDeXinMiMa: "请输入正确的新密码",
                qingShuRuQueRenMiMa: "请输入确认密码",
                qingShuRuZhengQueDeQueRenMiMa: "请输入正确的确认密码",
                qingShuRuDuanXinYanZhengMa: "请输入短信验证码",
                qingShuRuZhengQueDeDuanXinYanZhengMa: "请输入正确的短信验证码",
                qingShuRuZhengShiXingMing: '请输入真实姓名',
                qingShuRuYouXiaoDeZhengShiXingMing: '请输入有效的真实姓名',
                qingShuRuShenFenZhengHao: '请输入身份证号',
                qingShuRuYouXiaoDeShenFenZhengHao: '请输入有效的身份证号',
                qingShuRuYingHangKaHao: '请输入银行卡号',
                qingShuRuYouXiaoDeYingHangKaHao: '请输入有效的银行卡号',
                qingXuanZeYingHang: '请选择银行',
                qingXuanZeYouXiaoDeYingHang: '请选择有效的银行',
                qingXuanZeXingBie: '请选择性别',
                qingXuanZeYouXiaoDeXingBie: '请选择有效的性别',
                qingXuanZeChuShengRiQi: '请选择出生日期',
                qingXuanZeYouXiaoChuShengRiQi: '请选择有效的出生日期',
                qingXuanZeShangChuanLeiXing: '请选择上传类型',
                qingXuanZeHuoPaiSheTuPian: '请选择或拍摄图片',
                qingXianWanShanRenLianHeZhengJianXingXi: '请先完善人脸识别和证件信息',
                qingShangChuanZhengJianZhengMianZhaoPian: '请上传证件正面照片',
                qingShangChuanZhengJianFanMianZhaoPian: '请上传证件反面照片',
                qingShangChuanZiPaiZhaoPian: '请上传自拍照片',
                queRenMiMaCuoWu: "确认密码错误",
                miMaShuoMing: '密码为6-16位字符,包含字母和数字',
                canShuCuoWu: "参数错误",
                caoZuoLeiXingCuoWu: '操作类型错误',
                huoQuYanZhengMa: "获取验证码",
                chongXingHuoQu: '重新获取',
                dengLuChengGong: "登录成功",
                biaoMingBeiZhu: '标明备注',
                beiZhuGeShi: '备注格式',
                yiJianFanKuiMiaoShu: '请输入您的反馈意见,我们会为您不断进步',
                yiRenZhengShiFouChongXiuRenZheng: '已认证，是否重新认证?',
                yingHangKaYiBangDingShiFouChongXiuRenZheng: '银行卡已绑定，是否重新认证?',
                zhengZaiShiBie: '正在识别',
                zhengZaiShangChuan: '正在上传'
            },
            user: {
                regist: "注册",
                login: "登录",
                logout: "退出",
                logout2: "退出登录",
                forgetPwd: "忘记密码?",
                loginPwd: "登录密码",
                tradePwd: "交易密码",
                jiZhuShouJiHao: "记住手机号",
                ningWeiDengLu: '您未登录',
                yuanMiMa: "原密码",
                xinMiMa: "新密码",
                queRenMiMa: "确认密码",
                shiFouTuiChuDengLu: '是否退出登录',
                woDeYaoQingMa: '我的邀请码',
                wanShanZiLiao: '完善资料',
                woYiYueDuBingTongYi: '我已阅读并同意',
                zhuCeXieYi: '《注册协议》',
                zhaoHuiMiMa: '找回密码',
                yaoQingHaoYou: '邀请好友',
                yaoQingJiLu: '邀请记录',
                woDeJiangJing: '我的奖金',
                daiFanJiangJin: '待返奖金',
                shouJiHao: '手机号',
                xingBie: '性别',
                xingMing: '姓名',
                dianHua: '电话',
                diZhi: '地址',
                guanXi: '关系',
                geRenZhengJian: '个人证件',
                renLianShiBie: '人脸识别',
                shiMingXingXi: '实名信息',
                geRenXingXi: '个人信息',
                youXiangDiZhi: '邮箱地址',
                zuiGaoXueLi: '最高学历',
                hunYinZhuangTai: '婚姻状态',
                xianJuDiZhi: '现居地址',
                xiangXiDiZhi: '详细地址',
                zhengShiXingMing: '真实姓名',
                shenFenZhengHao: '身份证号',
                chuShengRiQi: '出生日期',
                zhiXiQingShu: '直系亲属',
                jingJiLianXiRen: '紧急联系人',
                gongZuoXingXi: '工作信息',
                gongSiMingCheng: '公司名称',
                gongSiDianHua: '公司电话',
                gongSiDiZhi: '公司地址',
                gongZuoNianXian: '工作年限',
                xinZi: '薪资',
                yingHang: '银行',
                zhangHuLeiXing: '账户类型',
                yingHangXinXi: '银行信息',
                suoShuYinHang: '所属银行',
                yingHangZhangHao: '银行账号',
                yingHangKaHao: '银行卡号',
                zhangHaoKaHao: '账号/卡号',
                shouKuanYingHangKa: '收款银行卡',
                chiKaRen: '持卡人',
                yunYingShangXingXi: '运营商信息',
                fackbookXingXi: 'Fackbook信息',
                shiMingXingXiTiShi1: '温馨提示：请如实填写您的姓名和身份证号码，如果您的姓名和身份证号码不实，系统审核不过，您将无法借款',
                yingHangKaTianJiaMiaoShu: '添加你的银行卡用于收款',
                yingHangKaoBangDingMiaoShu1: '1.借款通过申请后,我们将会将你的所借款项发放到该张银行卡',
                yingHangKaoBangDingMiaoShu2: '2.若申请重新绑卡，则新卡将激活为收款银行卡',
                yingHangKaoBangDingMiaoShu3: '3.未完成借款期间不允许更换银行卡',

            },
            bus: {
                timesu: '天', //借款时长 单位
                yuan: '元',
                eDu: '额度',
                jieKuan: '借款',
                huanKuan: '还款',
                sheYuKeJie: "剩余可借",
                jieKuanJiLu: '借款记录',
                yingHangZhuanZhang: '银行转账',
                yingHangZhuanZHngShuoMing1: '请将还款金额转至以下银行账户中并',
                yingHangZhuanZHngShuoMing2: '您的姓名+手机号',
                ziZhuHuanKuan: '自助还款',
                zaloHuanKuan: 'ZALO还款',
                huanKuanFangShiTiShi: '支持多种还款方式，方便快捷',
                meiYouJieKuanJiLuTiShi: '您还没有借款记录哦~~~',
                meiYouHuanKuanXinXiTiShi: '您现在还没有要还的贷款哦~',
                shouKuanRen: '收款人',
                shouKuanHang: '收款行',
                jieKuanXinXi: '借款信息',
                jingDuXinXi: '进度信息',
                jingKuanJinge: '借款金额',
                jieKuanLiXi: '借款利息',
                jieKuanXieYi: '《借款协议》',
                fuWuFei: '服务费',
                huanKuan: '还款',
                huanKuanXinXi: '还款信息',
                huanKuaiChengGong: '还款成功',
                huanKuanShiJian: '还款时间',
                huanKuanZongE: '还款总额',
                jieKuanShiChang: '借款时长',
                jieKuanShiJian: '借款时间',
                shiJiDaoZhang: '实际到账',
                liJiHuanKuan: '立即还款',
                ningBengCiHuanKuanJingEYou: '您本次的还款金额有',
                yingHuanJinge: '应还金额',
                yingHuanShiJian: '应还时间',
                yuQiShiJian: '逾期时间',
                yuQiZhiNaiJing: '逾期滞纳金',
                huanKuanTiShi1: '温馨提示：请确认您绑定的银行卡账户余额满足当前的还款总数额，如您的账户余额不足导致还款失败,逾期费用请自行承担',
                borrowStatus10: '审核中',
                borrowStatus20: '自动审核成功',
                borrowStatus21: '自动审核不通过',
                borrowStatus22: '自动审核未决待人工复审',
                borrowStatus26: '人工复审通过',
                borrowStatus27: '人工复审不通过',
                borrowStatus30: '待还款',
                borrowStatus35: '展期',
                borrowStatus40: '已还款',
                borrowStatus41: '减免还款',
                borrowStatus50: '已逾期',
                epayHuanKuan: 'epay还款',
                shouKuanZhangHao: '收款账号',
                huanKuanTiShi: '请在截至日期前还款',
                zhangHaoBuCunZi: '账号不存在',
                epayHuanKuanTiShi1: '请确认你的账号余额足够',
                epayHuanKuanTiShi2: '如果余额不足，将导致还款失败！',
                huanKuanLiuCheng:'还款流程'
            }
        }
    }
}

export default langs;
